name: radio-pwa-templates
services:
  - name: radio-pwa
    image: 
      context: .
      dockerfile: Dockerfile
    domains:
      - host: tu-dominio.com
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3000"
    ports:
      - published: 80
        target: 3000
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s